### ISSUE TITLE
Make setup on fresh linux install is broken

### ISSUE THREAD

**Issue by zefram-cochrane** [XSCALE-Alliance/XSCALE-Alliance.github.io#42]
I haven't tried to do anything on the site since moving to manjaro but wanted to tinker with a couple of things today so ...

 make setup
 assumptions:
 - a ruby environment
echo "2.5" > .ruby-version
gem install bundler
Fetching bundler-2.1.4.gem
/home/pete/.rvm/rubies/ruby-2.5.5/lib/ruby/gems/2.5.0/gems/gem-wrappers-1.4.0/lib/gem-wrappers/installer.rb:56: warning: Insecure world writable dir /home/pete in PATH, mode 040777
Successfully installed bundler-2.1.4
Parsing documentation for bundler-2.1.4
Installing ri documentation for bundler-2.1.4
Done installing documentation for bundler after 2 seconds
1 gem installed
bundle install
The dependency wdm (~> 0.1.0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mswin32, x86-mingw32. To add those platforms to the bundle, run `bundle lock --add-platform x86-mswin32 x86-mingw32`.
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mswin32, x86-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mswin32 x86-mingw32 java`.
Fetching gem metadata from https://rails-assets.org/..
Fetching gem metadata from http://rubygems.org/............
Fetching gem metadata from https://rails-assets.org/..
Fetching concurrent-ruby 1.1.5
Installing concurrent-ruby 1.1.5
Using i18n 0.9.5
Using minitest 5.14.0
Using thread_safe 0.3.6
Using tzinfo 1.2.6
Using activesupport 5.0.7.2
Using public_suffix 4.0.3
Using addressable 2.7.0
Fetching backports 3.15.0
Installing backports 3.15.0
Using builder 3.2.4
Using bundler 2.1.4
Using chunky_png 1.3.11
Using coffee-script-source 1.12.2
Using execjs 2.7.0
Using coffee-script 2.4.1
Using multi_json 1.14.1
Using sass 3.4.25
Using compass-core 1.0.3
Using compass-import-once 1.0.5
Using rb-fsevent 0.10.3
Using ffi 1.12.2
Using rb-inotify 0.10.1
Using compass 1.0.3
Using contracts 0.13.0
Using dotenv 2.7.5
Using eventmachine 1.2.7
Using http_parser.rb 0.6.0
Using em-websocket 0.5.1
Using erubis 2.7.0
Using ethon 0.12.0
Using fast_blank 1.0.0
Using fastimage 2.1.7
Using font-awesome-sass 4.7.0
Using temple 0.8.2
Using tilt 2.0.10
Using haml 5.1.2
Using hamster 3.0.0
Using hashie 3.6.0
Using mercenary 0.4.0
Using mini_portile2 2.4.0
Using nokogiri 1.10.8
Using nokogumbo 2.0.2
Using parallel 1.19.1
Using rainbow 3.0.0
Using typhoeus 1.3.1
Fetching yell 2.2.1
Installing yell 2.2.1
Using html-proofer 3.15.1
Using kramdown 1.17.0
Using listen 3.0.8
Using memoist 0.16.2
Using thor 1.0.1
Using middleman-cli 4.3.5
Using padrino-support 0.13.3.4
Using padrino-helpers 0.13.3.4
Fetching rack 2.1.2
Installing rack 2.1.2
Fetching sassc 2.1.0 (x86_64-linux)
Installing sassc 2.1.0 (x86_64-linux)
Using servolux 0.13.0
Using uglifier 3.2.0
Using middleman-core 4.3.5
Using middleman 4.3.5
Using middleman-blog 4.0.3
Using middleman-compass 4.0.1
Using net-ssh 5.2.0
Using net-sftp 2.1.2
Using ptools 1.3.5
Using middleman-deploy 2.0.0.pre.alpha
Using middleman-jquery 2.1.1
Using rack-livereload 0.3.17
Using middleman-livereload 3.4.6
Using middleman-metaman 0.1.9
Using sprockets 3.7.2
Using middleman-sprockets 4.1.1
Using rails-assets-Hover 1.0.9
Using rails-assets-jquery 3.4.1
Using rails-assets-formstone 0.6.14
Using rails-assets-html5shiv 3.6.2
Using rails-assets-jquery.easing 1.3.1
Using rails-assets-jquery.scrollex 0.2.1
Using rails-assets-jquery.stellar 0.6.2
Using rails-assets-mapbox.js 2.1.9
Using rails-assets-respond 1.4.2
Using rails-assets-skel 3.0.1
Using slim 4.0.1
Bundle complete! 26 Gemfile dependencies, 83 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
pete@phileas:~/src/xscalealliance.org$ make server
bundle exec middleman server
Deprecation warning: Expected string default value for '--instrument'; got false (boolean).
This will be rejected in the future unless you explicitly pass the options `check_default_type: false` or call `allow_incompatible_default_type!` in your code
You can silence deprecations warning by setting the environment variable THOR_SILENCE_DEPRECATION.
Traceback (most recent call last):
        20: from /home/pete/.rvm/gems/ruby-2.5.5/bin/ruby_executable_hooks:24:in `<main>'
        19: from /home/pete/.rvm/gems/ruby-2.5.5/bin/ruby_executable_hooks:24:in `eval'
        18: from /home/pete/.rvm/gems/ruby-2.5.5/bin/middleman:23:in `<main>'
        17: from /home/pete/.rvm/gems/ruby-2.5.5/bin/middleman:23:in `load'
        16: from /home/pete/.rvm/gems/ruby-2.5.5/gems/middleman-cli-4.3.5/bin/middleman:10:in `<top (required)>'
        15: from /home/pete/.rvm/gems/ruby-2.5.5/gems/middleman-core-4.3.5/lib/middleman-core/load_paths.rb:15:in `setup_load_paths'
        14: from /home/pete/.rvm/gems/ruby-2.5.5/gems/middleman-core-4.3.5/lib/middleman-core/load_paths.rb:35:in `setup_bundler'
        13: from /home/pete/.rvm/gems/ruby-2.5.5/gems/bundler-2.1.4/lib/bundler.rb:174:in `require'
        12: from /home/pete/.rvm/gems/ruby-2.5.5/gems/bundler-2.1.4/lib/bundler/runtime.rb:58:in `require'
        11: from /home/pete/.rvm/gems/ruby-2.5.5/gems/bundler-2.1.4/lib/bundler/runtime.rb:58:in `each'
        10: from /home/pete/.rvm/gems/ruby-2.5.5/gems/bundler-2.1.4/lib/bundler/runtime.rb:69:in `block in require'
         9: from /home/pete/.rvm/gems/ruby-2.5.5/gems/bundler-2.1.4/lib/bundler/runtime.rb:69:in `each'
         8: from /home/pete/.rvm/gems/ruby-2.5.5/gems/bundler-2.1.4/lib/bundler/runtime.rb:74:in `block (2 levels) in require'
         7: from /home/pete/.rvm/gems/ruby-2.5.5/gems/bundler-2.1.4/lib/bundler/runtime.rb:74:in `require'
         6: from /home/pete/.rvm/gems/ruby-2.5.5/gems/sassc-2.1.0-x86_64-linux/lib/sassc.rb:31:in `<top (required)>'
         5: from /home/pete/.rvm/gems/ruby-2.5.5/gems/sassc-2.1.0-x86_64-linux/lib/sassc.rb:31:in `require_relative'
         4: from /home/pete/.rvm/gems/ruby-2.5.5/gems/sassc-2.1.0-x86_64-linux/lib/sassc/native.rb:3:in `<top (required)>'
         3: from /home/pete/.rvm/gems/ruby-2.5.5/gems/sassc-2.1.0-x86_64-linux/lib/sassc/native.rb:3:in `require'
         2: from /home/pete/.rvm/gems/ruby-2.5.5/gems/ffi-1.12.2/lib/ffi.rb:3:in `<top (required)>'
         1: from /home/pete/.rvm/gems/ruby-2.5.5/gems/ffi-1.12.2/lib/ffi.rb:6:in `rescue in <top (required)>'
/home/pete/.rvm/gems/ruby-2.5.5/gems/ffi-1.12.2/lib/ffi.rb:6:in `require': libffi.so.6: cannot open shared object file: No such file or directory - /home/pete/.rvm/gems/ruby-2.5.5/gems/ffi-1.12.2/lib/ffi_c.so (LoadError)
make: *** [makefile:11: server] Error 1

**Comment by zefram-cochrane** [comment]
I did "gem install ffi" and everything seems to be working.

**Comment by serra** [comment]
I'll check it out by doing a clean checkout and setup on my machine.In the meantime, this issues serves as a good pointer when others run into similar issues.

**Comment by serra** [comment]
The ffi library is a dependency of Middleman (through listen and sassc gems) so it is a bit surprising that it is not installed with the first `bundle install`. Hm.

**Comment by serra** [comment]
A clean checkout and build works on my machine and on our CI system. I'm not sure why it did not on your fresh linux install. Since you have resolved the issue, I'm assuming it has to do with your local setup and will close this issue.
